### ISSUE TITLE
Modify default Key

### ISSUE THREAD

**Issue by jdesherlia** [envkey/envkey-node#27]
Hi There. We have been using envKey for a while now, and are very happy. One thing that I always thought would be useful though, was the ability to do something like the following:
```
const envKey = require( `envkey` )
envKey.load( process.env.ENVKEY_2)
```
The use case is, we have branch deploys turned on in Netlify, with our production site. Those all get Production env vars by default, because the ENVKEY we use is locked to the production environment in envKey. Not typically a big deal, but on our develop branch deploys, we need to have the values from the develop environment, primarily for working with other non-prod apis for unit testing. Rather than stand up an entirely different netlify site just so that I can add a different ENVKEY, we would like to be able to just add a second one, ENVKEY_DEV with a key that is bound to the develop environment. Then, based on deploy contexts, we can decide which one to use when loading envKey.

We have been doing this by simply overwriting the main key:
```
if ( devInProd ) {
      process.env.ENVKEY = process.env.ENVKEY_DEV
}
```
However, that stopped working recently. Not sure why... I suspect it has to do with build optimizations on Netlify. But being able to configure which environment variable envkey uses to fetch data would be nice.

Thanks!
-Josh-

**Comment by jdesherlia** [comment]
@danenania any idea if this is doable?

**Comment by danenania** [comment]
Hey @jdesherlia,

This is definitely a bit tough to do with envkey-node currently given how the `ENVKEY` is loaded. A couple options that could work:

- Separate out your dev and prod variables. Instead of just `SERVICE_API_KEY`, make a `DEV_SERVICE_API_KEY` and a `PROD_SERVICE_API_KEY`. Then for your production environment, set `DEV_SERVICE_API_KEY` it to inherit from development in the EnvKey UI. The drawback here would be that you'd have to detect that you're running in development and use the `DEV` version of those variables.

- Perhaps you could also use [envkey-source](https://github.com/envkey/envkey-source) to inject the variables from the shell instead of in-process with envkey-node. `envkey-source` can be supplied an `ENVKEY` directly instead of relying on an environment variable, so it's easier to load more than one `ENVKEY` for this kind of use case.
