### ISSUE TITLE
Cannot access environment variables while offline

### ISSUE THREAD

**Issue by selenium-tester** [envkey/envkey-node#3]
OS: MacOS 10.12.6
Node: 8.11.1
EnvKey Node Client: 1.1.1
EnvKey Desktop Client: 1.3.4

I was doing a quick proof of concept test and trying out your product features. In the docs it says EnvKey will work offline, but when I tried to do so I get the following message:

` throw "ENVKEY invalid. Couldn't load vars."`

This happens when attempting to request both Staging or Production keys (.env file or environment export) while offline (WiFi disabled). It appears that there was no ".envkey" folder created in my home directory for the local cache to be stored in, which might explain it.

**Comment by danenania** [comment]
Did you first load the ENVKEY with a working connection? For the cache to be filled (and be available for offline use), it needs to first be loaded successfully with a connection. Also, since caching is only enabled in development, `process.env.NODE_ENV` has to be either "development" or "test".  Let me know if this explains it. Thanks!

**Comment by selenium-tester** [comment]
Yes, it works successfully while online. Setting my NODE_ENV to "development" got it working offline. Thanks!
